# Generated by Django 3.1.5 on 2021-01-16 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='识别时间')),
                ('image', models.TextField(verbose_name='图片base64')),
                ('result', models.TextField(verbose_name='返回值')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '识别记录',
                'verbose_name_plural': '识别记录',
            },
        ),
    ]
